# These are supported funding model platforms

github: NamNamIoT
patreon: NamNamIoT
open_collective: NamNamIoT
ko_fi: NamNamIoT
tidelift: NamNamIoT
community_bridge: NamNamIoT
liberapay: NamNamIoT
issuehunt: NamNamIoT
otechie: NamNamIoT
lfx_crowdfunding: NamNamIoT
custom: NamNamIoT
